[D-3] ProductsView 화면 구현
O-market/O-market pull request #32
Opened 2022-09-02 09:47 UTC by FirstDo

### 배경

- 이슈:  #23 

### 작업 내용

- 상품 리스트들을 보여주는 ViewController, ViewModel, Coordinator 구현
- 기타 ProductCell, ProductCellViewModel style, font 등 수정이 있습니다

### 테스트 방법

### 리뷰 노트

어색한 부분/ 잘못된 부분 / 개선할 수 있는 부분 언제든 환영입니다 :)
기간 넉넉하게 했어요 월요일까지만 확인해주세요

filter와 testCode는 추가로 구현할 예정입니다 (된다면 searchBar까지.. 가능성 1퍼)

### 스크린샷 및 영상

|제목|
|:---:|
|<img src = "https://user-images.githubusercontent.com/69573768/188112916-c90b5227-b56c-4117-8e2e-867e5329c40e.png" width = "300">|

2022-09-03 08:45 UTC, llingo requested changes
[P1~3] 부분 위주로 변경하시고 다시 리뷰요청 하시면 바로 Approve 하겠습니다 🎉

2022-09-03 08:45 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/MainScene/ProductsScene/Coordinator/ProductsCoordinator.swift
> +    viewControler.coordinator = self
[P3] viewControler -> viewController으로 변경해야할 것 같습니다 :)

2022-09-03 08:45 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/MainScene/ProductsScene/ProductsViewModel.swift
> +    }
[P4] `self`보단 wself나 owner로 하는 것이 헷갈리지 않을 것 같습니다

2022-09-03 08:45 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/MainScene/ProductsScene/Coordinator/ProductsCoordinator.swift
> +    navigationController.pushViewController(viewControler, animated: true)
coordinator를 주입해주는 곳을 viewModel로 할지 viewController로 할지 이야기 해보면 좋을 것 같습니다.

2022-09-03 08:45 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/MainScene/ProductsScene/ProductsViewController.swift
> +    }
[P4] 아래와 같은 형태는 어떠신가요?

```swift
viewModel.products
  .bind(to: view.productsCollectionView.rx.items(
    cellIdentifier: ProductCell.identifier,
    cellType: ProductCell.self
  )) { _, item, cell in
    cell.bind(with: ProductCellViewModel(product: item))
  }
```

2022-09-03 08:45 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/MainScene/ProductsScene/ProductsViewController.swift
> +    }
[P4] 메인화면에서 Section이 2개이고 RxDataSource를 사용하다보니 ProductSectionItemType로 추상화해서 사용했는데 이 부분에 대해 나중에 이야기 해보면 좋을 것 같습니다 :)

2022-09-03 08:45 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/MainScene/ProductCell/ProductCellViewModel.swift
> +    return percentage == 0 ? "1%" : "\(percentage)%"
이 부분이 저번에 사파리와 이야기했던 부분이군요 :)

2022-09-03 08:45 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/MainScene/ProductsScene/ProductsViewModel.swift
> +protocol ProductsViewModelOutout {
[P3] 오타 발견 👀
 ProductsViewModelOutout -> ProductsViewModelOutput

2022-09-03 14:42 UTC, FirstDo commented on Projects/OmarketApp/Sources/Presentation/MainScene/ProductsScene/ProductsViewModel.swift
> +protocol ProductsViewModelOutout {
감사 :)

2022-09-03 14:44 UTC, FirstDo commented on Projects/OmarketApp/Sources/Presentation/MainScene/ProductsScene/ProductsViewModel.swift
> +    }
일단 다 그냥 withUnretained를 제거했습니다
이것도 통일하면 좋을것 같네요

2022-09-03 14:44 UTC, FirstDo commented on Projects/OmarketApp/Sources/Presentation/MainScene/ProductsScene/Coordinator/ProductsCoordinator.swift
> +    viewControler.coordinator = self
수정완료

2022-09-03 16:40 UTC, saafaaari approved these changes
두두 너무 고생하셨습니다.!!!
코멘트를 하나 달았는데 개인적인 의견이라 틀린 정보일 수 있습니다.
두두도 생각이 같다면, 적용해주세요.

2022-09-03 16:40 UTC, saafaaari commented on Projects/OmarketApp/Sources/Presentation/MainScene/ProductsScene/ProductsViewModel.swift
> +  var showProductDetailScene: PublishRelay<Product> { get }
[P5] 타입을 Observable로 통일해도 괜찮을것 같아요.
private로 Relay를 만들고, Observable로 형변환한 프로퍼티를 외부로 노출시켜 bind를 시켜도 뿌리가 Relay이기 때문에 에러를 방출하지 않는 Observable가 될것 같아요.(이건 검증되지 않은 개인적인 생각입니다.)
Output protocol 프로퍼티 타입을 Observable로하면 추후 가짜 객체를 생성할때 용이할것 같아요.

2022-09-04 10:10 UTC, llingo approved these changes
두두 수고하셨습니다 💯

2022-09-06 06:18 UTC, merged