[D-3] 상품 수정 화면 및 기능 구현
O-market/O-market pull request #60
Opened 2022-11-08 09:18 UTC by saafaaari

### 배경

- 이슈: #58 

### 작업 내용
- Editing V, VC, VM, C 구현
- UIbind를 위한 EditingViewModelItem 구현
- Product Model 수정
- DetailVM Product 프로퍼티 추가
- Detail -> Editing 화면 이동 구현

### 테스트 방법
viewModel 테스트 진행 예정

### 리뷰 노트
상품 수정을 위한 화면 및 기능을 구현하였습니다.
테스트는 머지전에 진행해서 같이 머지하도록 하겠습니다.

### 스크린샷 및 영상

| 구현 화면 |
|:---:|
| <img src="https://user-images.githubusercontent.com/91936941/200524360-90d1e783-6460-4bb2-b620-0f11a734fe1d.gif" width="200"> |

2022-11-15 13:17 UTC, llingo requested changes
@saafaaari 

수고하셨습니다 사파리 EditingCoordinator에서 강한 순환참조가 생길 가능성이 있는 것 같아요.
수정 부탁드립니다 :)

2022-11-15 13:17 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/Writing/Coordinator/EditingCoordinator.swift
> +  var navigationController: UINavigationController
var 로 구현하신 이유가 있나요?

2022-11-15 13:17 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/Writing/Coordinator/EditingCoordinator.swift
> +  var parentCoordinator: Coordinator?
[P3] 강한 순환 참조가 발생할 가능성이 있을 것 같아요 `weak var`가 좋아보입니다

2022-11-16 07:29 UTC, saafaaari commented on Projects/OmarketApp/Sources/Presentation/Writing/Coordinator/EditingCoordinator.swift
> +  var navigationController: UINavigationController
아차차 체크를 못했네요. Creation 쪽에도 var로 되어 있어 같이 수정 했습니다.

2022-11-16 08:37 UTC, llingo approved these changes
@saafaaari 

수고하셨습니다 사파리 :)

2022-11-16 12:15 UTC, merged