[D-2] MSImagePicker -> SFImagePicker로 대체
O-market/O-market pull request #62
Opened 2022-11-16 15:37 UTC by saafaaari

### 배경
기존 MSImagePicker를 SFImagePicker로 대체

- 이슈: #61 

### 작업 내용
- Tuist SFImagePicker 추가
- MSImagePicker 삭제
- Creation 간단 리팩토링

### 리뷰 노트
SFImagePicker로 대체 하였으며, MSImagePicker와 SFImagePicker 사용 방법에 따른 차이가 있어 일부 Controller및 ViewModel 로직이 수정되었습니다.

2022-11-16 17:54 UTC, llingo requested changes
@saafaaari 

ImageView 라는 클래스명이 사용자(개발자) 입장에서 혼란이 될 수 있는 이름인 것 같아요.
MSImagePicker를 라이브러리화 하여 추가해주셨군요. 👍 수고하셨습니다!

2022-11-16 17:54 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/Writing/Coordinator/CreationCoordinator.swift
> +      onCancel: onCancel
[P4] onSelected, onDeSelected, onCanceled 는 어떠신가요?

2022-11-16 17:54 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/Writing/View/ImageView.swift
>  final class ImageView: UIView {
[P3] 내부 프로퍼티 네이밍이 imageView이기 때문에 클래스명까지 ImageView면 사용자 입장에서 혼란이 있을 것 같아요

2022-11-16 17:54 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/Writing/ViewModel/CreationViewModel.swift
> +  func selectedImageData(_ newData: ImageData)
[P4] 아래와 같은 파라미터 네이밍은 어떤가요?
```swift
func selectedImageData(_ imageData: ImageData) { ... }
```

2022-11-17 14:05 UTC, saafaaari commented on Projects/OmarketApp/Sources/Presentation/Writing/View/ImageView.swift
>  final class ImageView: UIView {
ProductImageView로 수정했습니다.

2022-11-18 05:18 UTC, llingo approved these changes
@saafaaari 

수고하셨습니다 사파리 :)

2022-11-18 08:07 UTC, merged