[D-3] 상품 삭제를 위한 API 및 기능 구현
O-market/O-market pull request #72
Opened 2022-11-21 12:47 UTC by saafaaari

### 배경

- 이슈: #70 

### 작업 내용
- 삭제를 위한 product URL 및 delete API 구현
- useCase, Repository, VM, VC 삭제에 필요한 메서드 구현
- Alert을 통한 삭제 의사 확인 

### 테스트 방법
Test 진행 예정

### 리뷰 노트
따로 비밀번호를 사용자가 입력하지 않고, 중첩으로 네트워크 통신하여 Alert 삭제 버튼을 클릭시 바로 삭제가 되도록 구현하였습니다.

### 스크린샷 및 영상

| 구현 화면 |
|:---:|
|<img src="https://user-images.githubusercontent.com/91936941/203058274-7651c888-cf48-467c-b90a-398399a9ce9e.gif" width="200">|

2022-11-21 12:59 UTC, saafaaari commented on Projects/OmarketApp/Sources/Presentation/Detail/ViewController/DetailViewController.swift
> +    }
위 같은 경우 클로저 내부 viewModel이 weak으로 캡쳐되어야 할지 애매한것 같습니다.
다른 화면도 확인해 봤는데 따로 viewModel을 캡쳐한 부분이 따로 없어 일단 PR올립니다.

2022-11-21 13:03 UTC, saafaaari commented on Projects/OmarketApp/Sources/Presentation/Detail/ViewModel/DetailViewModel.swift
> +
```swift
func deleteButtonDidTap() -> Completable {
    return Completable.create { completable in
      guard let self = self else { return }
      self.useCase.productURL(id: self.productId, password: UserInformation.password)
        .bind {
          self.useCase.deleteProduct(url: $0)
            .subscribe { _ in
              completable(.completed)
            } onError: { error in
              completable(.error(error))
            }.disposed(by: self.disposeBag)
        }.disposed(by: self.disposeBag)
      return Disposables.create()
    }
  }
```
위와 같이 Completable를 반환하여 VC에서 Error를 처리할 생각이었지만, 컴파일 에러가 발생해서 파라미터로 클로저를 받는 방식으로 구현하였습니다.

2022-11-21 13:09 UTC, saafaaari commented on Projects/OmarketApp/Sources/Presentation/Detail/ViewController/DetailViewController.swift
> +}
위 같은 경우 클로저 내부 viewModel이 weak으로 캡쳐되어야 할지 애매한것 같습니다.
다른 화면도 확인해 봤는데 따로 viewModel을 캡쳐한 부분이 따로 없어 일단 PR올립니다.

2022-11-21 13:10 UTC, saafaaari commented on Projects/OmarketApp/Sources/Presentation/Detail/ViewController/DetailViewController.swift
> +}
아니면, 메서드의 파라미터를 제거하고 self를 캡쳐하는 방향으로 수정해볼까요??

2022-11-21 13:31 UTC, llingo requested changes
@saafaaari 

수고하셨습니다 사파리
수정이 필요한 사안의 경우 코멘트 남겼습니다! 사파리께서 질문 주신 부분에 대해 코멘트를 남기긴 했는데 좋은 방법인지는 좀 더 고민해봐야할 것 같네요

2022-11-21 13:31 UTC, llingo commented on Projects/OmarketApp/Sources/Data/Repository/ProductRepositoryImpl.swift
> +      .map { String(decoding: $0, as: UTF8.self) }
[P4] `String(data: $0, encoding: .utf8)`랑 다른 점이 있나요? 처음보는 생성자군요

2022-11-21 13:31 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/Detail/ViewModel/DetailViewModel.swift
> +    errorHandler: @escaping ((Error) -> Void)
[P4] `@escaping () -> Void`, `@escaping (Error) -> Void`이 더 좋을 것 같아요

2022-11-21 13:31 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/Detail/ViewController/DetailViewController.swift
> +}
Alert와 Action을 Observable 형태로 해서 ViewModel -> View 스트림 형태로 가도록 하면 viewModel을 내부에서 쓸 필요가 없지 않을까요?

2022-11-21 13:31 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/Detail/ViewModel/DetailViewModel.swift
> +
flatMap을 활용하면 가능할 것 같습니다.

```swift
func deleteButtonDidTap() {
  useCase.productURL(id: self.productId, password: UserInformation.password)
    .withUnretained(self)
    .flapMap { owner, url in owner.useCase.deleteProduct(url: url) }
    .subscribe(onNext: {
      //...
    }, onError: {
      //...
    })
    .disposed(by: disposeBag)
}

```

2022-11-23 03:20 UTC, llingo requested changes
@saafaaari 

수고하셨습니다 사파리 👍 Alert 부분이 매우 깔끔해졌군요

2022-11-23 03:20 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/Detail/ViewController/DetailViewController.swift
>          }
ActionSheet에서 작성해주신 방식이 forEach 돌리는 것보다 더 가독성이 좋아보이네요 :)

```swift
let editAction = UIAlertAction(title: "수정", style: .default) { _ in
  single(.success("수정"))
}
let deleteAction = UIAlertAction(title: "삭제", style: .destructive) { _ in
  single(.success("삭제"))
}
let cancelAction = UIAlertAction(title: "취소", style: .cancel) { _ in
  single(.success("취소"))
}
```

2022-11-23 03:20 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/Detail/ViewModel/DetailViewModel.swift
> +  var deleteAction: PublishRelay<Void> { get }
Relay가 밖으로 노출되면 외부에서 accept로 데이터를 변경이 가능할 수 있을 것 같습니다.

2022-11-23 03:20 UTC, llingo commented on Projects/OmarketApp/Sources/Presentation/Detail/ViewController/DetailViewController.swift
> +      ).disposed(by: disposeBag)
엄청 깔끔해졌군요 👍

2022-11-23 06:56 UTC, llingo approved these changes
@saafaaari 

수고하셨습니다 👍

2022-11-23 11:40 UTC, merged